# Generated by Django 4.0.4 on 2022-04-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qalampiruz', '0003_news_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
